#!/usr/bin/env python3
"""
Apply the version-controlled iOS project overlay to gen/apple/project.yml.

`gen/` is generated and gitignored, but the generated project.yml is not the
whole truth: file associations, Files-app support, the #139 open-in-place fix,
several build settings and the signing configuration were all typed into it by
hand and existed on exactly one disk. `tauri ios init` rewrites that file
whenever it is absent, so a single regeneration silently dropped all of it.

This moves that knowledge into `app/src-tauri/ios-project-overlay.yml` and
re-applies it, so a regenerated project is a complete project.

Why an overlay rather than a committed project.yml: the generator owns the
parts that track the app — version strings, sources, frameworks, the
deployment target from tauri.conf.json. Pinning the whole file would freeze
those and quietly undo them on the next Tauri upgrade.

Run it as many times as you like; it converges.
"""

import os
import re
import sys

try:
    import yaml
except ModuleNotFoundError:
    sys.exit("ERROR: this needs PyYAML — `python3 -m pip install --user pyyaml`.\n"
             "       (Only the local iOS build uses it; nothing in CI does.)")

ENV_REF = re.compile(r"\$\{([A-Z_][A-Z0-9_]*)\}")


def expand(value, required):
    """Substitute ${VAR} from the environment. The signing identity and team
    are per-machine and already live in .env.local; the overlay refers to them
    rather than hard-coding one developer's account into the repository."""
    if isinstance(value, str):
        def sub(m):
            got = os.environ.get(m.group(1))
            if not got:
                required.append(m.group(1))
                return m.group(0)
            return got
        return ENV_REF.sub(sub, value)
    if isinstance(value, dict):
        return {k: expand(v, required) for k, v in value.items()}
    if isinstance(value, list):
        return [expand(v, required) for v in value]
    return value


def walk(root, dotted, create=False):
    """Resolve 'targets.solomd_iOS.preBuildScripts.0.script' to (container, key).
    Numeric segments index lists."""
    node, parts = root, dotted.split(".")
    for part in parts[:-1]:
        key = int(part) if part.isdigit() else part
        try:
            node = node[key]
        except (KeyError, IndexError, TypeError):
            if not create:
                return None, None
            node[key] = {}
            node = node[key]
    last = parts[-1]
    last = int(last) if last.isdigit() else last
    return node, last


def deep_merge(base, over):
    for k, v in over.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            deep_merge(base[k], v)
        else:
            base[k] = v


def main():
    project = sys.argv[1] if len(sys.argv) > 1 else "app/src-tauri/gen/apple/project.yml"
    overlay_path = sys.argv[2] if len(sys.argv) > 2 else "app/src-tauri/ios-project-overlay.yml"

    with open(project, encoding="utf-8") as fh:
        doc = yaml.safe_load(fh)
    with open(overlay_path, encoding="utf-8") as fh:
        overlay = yaml.safe_load(fh)

    required = []
    overlay = expand(overlay, required)
    if required:
        sys.exit("ERROR: the overlay refers to environment variables that are not set: "
                 + ", ".join(sorted(set(required)))
                 + "\n       They normally come from .env.local.")

    deep_merge(doc, overlay.get("merge", {}))

    # `prepend` exists so we do not pin a value the generator owns: the Rust
    # build command is Tauri's, and only the PATH in front of it is ours.
    for dotted, prefix in (overlay.get("prepend") or {}).items():
        node, key = walk(doc, dotted)
        if node is None or (isinstance(node, dict) and key not in node):
            sys.exit(f"ERROR: prepend target {dotted} is not in {project}.\n"
                     f"       The generator's layout changed — check the overlay "
                     f"against a freshly generated project.yml.")
        current = node[key] or ""
        if prefix.strip() not in current:
            node[key] = prefix + current

    for rule in overlay.get("remove") or []:
        node, key = walk(doc, rule["path"])
        if node is None or not isinstance(node.get(key), list):
            continue
        match = rule["match"]
        node[key] = [item for item in node[key]
                     if not (isinstance(item, dict)
                             and all(item.get(k) == v for k, v in match.items()))]

    with open(project, "w", encoding="utf-8") as fh:
        fh.write("# Generated by `tauri ios init`, then patched by\n"
                 "# scripts/lib/ios_project_overlay.py from\n"
                 f"# {overlay_path} — edit the overlay, never this file.\n")
        yaml.safe_dump(doc, fh, sort_keys=False, allow_unicode=True, width=10000,
                       default_flow_style=False)
    print(f"overlay applied to {project}")


if __name__ == "__main__":
    main()
